### ISSUE TITLE
Unable to fetch service principal token error

### ISSUE THREAD

**Issue by jeremymaya** [Azure/Synapse-workspace-deployment#7]
Hello,

I am trying [deploy synapse artifacts](https://github.com/jeremymaya/arm-playground/runs/2530666957?check_suite_focus=true) using this GitHub Actions but currently getting the following error:

```bash
Unable to fetch service principal token, status: 404; status message: Not Found

(node:2160) UnhandledPromiseRejectionWarning: Error
    at Object.<anonymous> (/home/runner/work/_actions/azure/synapse-workspace-deployment/v0.1/dist/index.js:1:147182)
    at step (/home/runner/work/_actions/azure/synapse-workspace-deployment/v0.1/dist/index.js:1:146139)
    at Object.next (/home/runner/work/_actions/azure/synapse-workspace-deployment/v0.1/dist/index.js:1:145424)
    at fulfilled (/home/runner/work/_actions/azure/synapse-workspace-deployment/v0.1/dist/index.js:1:144924)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I checked I was getting a valid response back with the same secret values using the following `curl` request by following this [documentation](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#--use-the-service-principals-azure-ad-access-token-to-access-the-databricks-rest-api):

```bash
curl -X GET -H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=client_credentials&client_id=<client-id>&resource=<management-resource-endpoint>&client_secret=<application-secret>' \
https://login.microsoftonline.com/<tenantid>/oauth2/token
```

I've used the following for `ADE` and `RDE` values:

* secret.ADE: `https://login.microsoftonline.com/<tenantid>/oauth2/token`
* secret.RDE: `https://management.core.windows.net/`

Do you have any ideas on what I am doing wrong??? 😢

**Comment by jeremymaya** [comment]
I was able to resolve the issue by using the following urls for `activeDirectoryEndpointUrl` and `resourceManagerEndpointUrl`:

* `activeDirectoryEndpointUrl` : https://login.microsoftonline.com/
* `resourceManagerEndpointUrl`: https://management.core.windows.net/
