### ISSUE TITLE
timeout while getting artifacts from workspace: deleting objects

### ISSUE THREAD

**Issue by indexample** [Azure/Synapse-workspace-deployment#70]
all of a sudden we get a this error while deploying our synapse workspace: Encountered with exception:Failed
it seems like a timeout issue while getting artifacts from the workspace, in order to determine the objects to delete. 

we have this checkbox checked: : Delete Artifacts Not In Template 

error log: 

```
Getting Artifacts from workspace: syn-xxxxxx-acc.
2022-11-04T09:35:31.6963870Z Failed to fetch artifacts from workspace:  Error: Request timeout: /databases?api-version=2019-06-01-preview
2022-11-04T09:35:31.6965497Z     at ClientRequest.req.setTimeout (D:\a\_tasks\Synapse workspace deployment_51060321-a461-4140-9787-xxxxxxxxxx\2.3.0\node_modules\typed-rest-client\HttpClient.js:324:26)
2022-11-04T09:35:31.6966289Z     at Object.onceWrapper (events.js:286:20)
2022-11-04T09:35:31.6966836Z     at ClientRequest.emit (events.js:198:13)
2022-11-04T09:35:31.6967348Z     at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
2022-11-04T09:35:31.6968255Z     at Object.onceWrapper (events.js:286:20)
2022-11-04T09:35:31.6968743Z     at TLSSocket.emit (events.js:198:13)
2022-11-04T09:35:31.6969232Z     at TLSSocket.Socket._onTimeout (net.js:443:8)
2022-11-04T09:35:31.6969685Z     at ontimeout (timers.js:436:11)
2022-11-04T09:35:31.6970168Z     at tryOnTimeout (timers.js:300:5)
2022-11-04T09:35:31.6970625Z     at listOnTimeout (timers.js:263:5)
2022-11-04T09:35:31.6971126Z deploy operation failed
2022-11-04T09:35:31.6971532Z An error occurred during execution: Failed
2022-11-04T09:35:31.7016579Z ##[error]Encountered with exception:Failed
2022-11-04T09:35:31.7112398Z ##[section]Finishing: Deploy Synapse Workspace V2
```

**Comment by lordozb** [comment]
Hello 
Please raise a support ticket on the Azure portal.

**Comment by lordozb** [comment]
Which region ? I can see some customers affected in WestEurope and team working to mitigate it

**Comment by Justin-FrenchIndustries** [comment]
Yep, also WestEurope, is there a status page that i can monitor this on?

**Comment by lordozb** [comment]
There is no status page for this but I am actively working to mitigate it, I am re opening the issue here and will update.

**Comment by Justin-FrenchIndustries** [comment]
Just to let you know this is also affecting North Europe

**Comment by indexample** [comment]
it seems fixed
2022-11-04T13:58:48.6359694Z Completed deploying artifacts from the template.
2022-11-04T13:58:48.6360191Z Attempting to delete artifacts from workspace, that were not in the template.
2022-11-04T13:58:48.6363038Z Getting Artifacts from workspace: syn-xxx-acc.
2022-11-04T13:58:55.3539134Z Found 284 artifacts in the workspace.
2022-11-04T13:58:55.3540189Z Getting Artifacts which should be deleted from workspace.
2022-11-04T13:58:55.3630960Z Found 0 artifacts in the workspace that many need to be deleted.

**Comment by lordozb** [comment]
Thanks for confirmation. Should be mitigated now in both North and West Europe.

**Comment by indexample** [comment]
thanks for the quick fix, next time dont close my issue ;) azure support ticket was raised and a 30 min call was spend on understanding the difference between synapse workspace pipelines and devops release pipelines ;)

**Comment by Justin-FrenchIndustries** [comment]
That's great thank you for the quick fix. And @indexample , I always have the same problem explaining to people about pipelines, you need to add the devops build pipelines into that list!!

**Comment by lordozb** [comment]
> thanks for the quick fix, next time dont close my issue ;) azure support ticket was raised and a 30 min call was spend on understanding the difference between synapse workspace pipelines and devops release pipelines ;)

I'll pass on this feedback to the support team. Thank you.
